### ISSUE TITLE
I love this theme so much!

### ISSUE THREAD

**Issue by Bluemoondragon07** [tazpellegrini/abyssalobsidian#3]
It's beautiful. I never think about paragraph or list spacing or anything when I'm programming css, but using this theme really opened up my eyes to the effects careful spacing can have on the viewer.

The colors, font weights, and tables are really nice-looking and well-done. The whole theme looks clean and unified. I like the contrast between the light and bold text in the file navigation pane. The beauty of the perfectly spaced lines are what really surprised me though! 

Good job on this theme, I'm stunned by the quality and detail.

**Comment by tazpellegrini** [comment]
Thank you so much for your detailed commentary and feedback! Coming from you, who made such impressive and inspiring themes, this means a lot to me! ❤️

As I get more comfortable with Obsidian theming, I want to make more improvements around some contextual situations (e.g: different list margins around some heading levels, etc) and give users more customization that aligns with the “baseline”, so it looks coherent without flooding them with options (I felt quite embarrassed only having two customization options but I decided that done was better than perfect).

**Comment by Bluemoondragon07** [comment]
Wow. I'm excited to see the contextual styling. You have a really good eye for design. 
I'm also looking forward to the styling options, but everything seems to be placed so carefully already I'd be nervous to tweak anything, haha.
Again, great job. I'm sure your theme will inspire many more people.

**Comment by tazpellegrini** [comment]
Thank you! That’s so thoughtful. But, feel free to mess around please, I’d love to learn from you. This isn’t the most elegant CSS I’ve ever written, so if you have any questions or suggestions etc, feel free to reach out here or somewhere on Discord (not very active there but I check sometimes) :D

**Comment by Bluemoondragon07** [comment]
Thanks. I only started learning CSS last month, so I don't know much.  I was actually about to look through the code to learn from you. But if I do come up with anything, I'll definitely share it with you!
